package main

import "testing"

func TestFormatsGo(t *testing.T) {
	testTranslationsGenerate(t, "go", map[string]string{
		"yaml8n.go": `// Package yaml8n contains generated translations.
// Code generated by YAML8n and covered under the
// Candid Public License; DO NOT EDIT.
//nolint:all
package yaml8n

import "strings"

// ISO639Code is used to lookup translations.
type ISO639Code string

// Translation contains translations for ISO639Codes.
type Translation map[ISO639Code]string

// Translate returns the translation for an ISO639Code.
func (t Translation) Translate(c ISO639Code) string {
	code := strings.Split(string(c), "-")[0]
	if s, ok := t[ISO639Code(code)]; ok {
		return s
	}

	return t["en"]
}

// HelloWorld contains Translations.
var HelloWorld = Translation{
	"de": ` + "`Hallo Welt`" + `,
	"en": ` + "`Hello World`" + `,
}

// TranslateMe contains Translations.
var TranslateMe = Translation{
	"en": ` + "`Translate Me`" + `,
}
`})
}
