package main

var goi18n = format{ //nolint:gochecknoglobals
	Extension:   "yaml",
	PerLanguage: true,
	Template: `# Code generated by YAML8n; DO NOT EDIT.

{{ range $name, $values := .Translations -}}
{{ range $code, $value := $values -}}
{{ if eq $code $.DefaultCode -}}
{{ $name }}:
  other: |
    {{ $value }}
{{ end -}}
{{- end }}
{{- end }}`,
}
