package main

import (
	"testing"
)

func TestFormatsTypescript(t *testing.T) {
	testTranslationsGenerate(t, "typescript", map[string]string{
		"yaml8n.ts": `/* eslint-disable */

// Code generated by YAML8n and covered under the
// Candid Public License; DO NOT EDIT.

export type ISO639Code = string;

export interface Translation {
	[key: ISO639Code]: string,
}

export const ISO639Codes: {
	[key: ISO639Code]: string,
} = {
	de: "Deutsch",
	en: "English",
};

export function Translate (c: ISO639Code, t: Translation): string {
	const code = c.split("-")[0];
	if (t[code] !== undefined) {
		return t[code];
	}

	return t["en"];
}

export const HelloWorld: Translation = {
	de: ` + "`Hallo Welt`" + `,
	en: ` + "`Hello World`" + `,
};

export const TranslateMe: Translation = {
	en: ` + "`Translate Me`" + `,
};
`,
	})
}
