package main

import "testing"

func TestFormatsGoi18n(t *testing.T) {
	testTranslationsGenerate(t, "goi18n", map[string]string{
		"en.yaml": `# Code generated by YAML8n; DO NOT EDIT.

HelloWorld:
  other: |
    Hello World
TranslateMe:
  other: |
    Translate Me
`,
		"de.yaml": `# Code generated by YAML8n; DO NOT EDIT.

HelloWorld:
  other: |
    Hallo Welt
`,
	})
}
