package main

var golang = format{ //nolint:gochecknoglobals
	Extension: "go",
	Template: `// Package {{ package }} contains generated translations.
// Code generated by YAML8n and covered under the
// Candid Public License; DO NOT EDIT.
//nolint:all
package {{ package }}

import "strings"

// ISO639Code is used to lookup translations.
type ISO639Code string

// Translation contains translations for ISO639Codes.
type Translation map[ISO639Code]string

// Translate returns the translation for an ISO639Code.
func (t Translation) Translate(c ISO639Code) string {
	code := strings.Split(string(c), "-")[0]
	if s, ok := t[ISO639Code(code)]; ok {
		return s
	}

	return t["{{ .DefaultCode }}"]
}
{{ range $name, $values := .Translations }}
// {{ $name }} contains Translations.
var {{ $name }} = Translation{
{{- range $code, $value := $values }}
{{- if ne $code "context" }}
	"{{ $code }}": ` + "`{{ $value }}`" + `,
{{- end }}{{ end }}
}
{{ end -}}
	`,
}
